# Generated by Django 5.2.9 on 2026-01-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_is_available_for_rent_car_listing_type_and_more'),
        ('payments', '0002_payment_delete_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cars.carbooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('STARTER', 'Starter Plan (KES 1,500)'), ('LITE', 'Lite Plan (KES 5,000)'), ('PRO', 'Pro Plan (KES 12,000)')], max_length=10, null=True),
        ),
    ]
