# Generated by Django 5.2.9 on 2026-01-04 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_carbooking_car_remove_carbooking_customer_and_more'),
        ('payments', '0003_payment_booking_alter_payment_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cars.booking'),
        ),
    ]
