# Generated by Django 5.2.9 on 2025-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Plan (3 Cars)'), ('PRO', 'Pro Plan (Unlimited)')], default='FREE', max_length=10),
        ),
    ]
