# Generated by Django 5.2.9 on 2025-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dealerprofile_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Plan (3 Cars)'), ('LITE', 'Biashara Lite (15 Cars)'), ('PRO', 'Showroom Pro (Unlimited)')], default='FREE', max_length=10),
        ),
    ]
