# Generated by Django 5.2.9 on 2025-12-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dealerprofile_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Business contact number', max_length=15, null=True),
        ),
    ]
