# Generated by Django 6.0 on 2025-12-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dealerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free (Inactive)'), ('STARTER', 'Starter (5 Cars)'), ('LITE', 'Lite (15 Cars)'), ('PRO', 'Pro (50 Cars)')], default='FREE', max_length=10),
        ),
    ]
