# Generated by Django 6.0 on 2025-12-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_dealerprofile_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='address',
            field=models.CharField(blank=True, help_text='e.g. 123 Ngong Road, Greenhouse Mall, Suite 4B', max_length=255),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Link to Google Maps location (for the button)', max_length=500),
        ),
    ]
