# Generated by Django 5.2.9 on 2026-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_dealer_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates a trusted/pro dealer (Blue Tick)'),
        ),
    ]
