# Generated by Django 5.2.9 on 2026-02-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dealerprofile_is_verified'),
        ('users', '0009_create_superuser'),
    ]

    operations = [
    ]
