# Generated by Django 6.0 on 2026-01-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, help_text='e.g. KDA 123X (Hidden from public)', max_length=20, null=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('RW', 'Rwanda'), ('SS', 'South Sudan'), ('ET', 'Ethiopia'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('EG', 'Egypt'), ('ZA', 'South Africa'), ('NA', 'Namibia'), ('AO', 'Angola'), ('GB', 'United Kingdom'), ('JP', 'Japan'), ('AE', 'United Arab Emirates')], default='KE', help_text='The country where this car is physically located.', max_length=2)),
                ('city', models.CharField(default='Nairobi', help_text='City or Town (e.g., Nairobi, Lagos, Accra)', max_length=100)),
                ('listing_currency', models.CharField(choices=[('KES', 'Kenyan Shilling (KES)'), ('UGX', 'Ugandan Shilling (UGX)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('RWF', 'Rwandan Franc (RWF)'), ('ETB', 'Ethiopian Birr (ETB)'), ('NGN', 'Nigerian Naira (NGN)'), ('GHS', 'Ghanaian Cedi (GHS)'), ('EGP', 'Egyptian Pound (EGP)'), ('ZAR', 'South African Rand (ZAR)'), ('NAD', 'Namibian Dollar (NAD)'), ('AOA', 'Angolan Kwanza (AOA)'), ('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)'), ('AED', 'UAE Dirham (AED)'), ('JPY', 'Japanese Yen (JPY)')], default='KES', help_text='Currency for the listed price.', max_length=3)),
                ('drive_side', models.CharField(choices=[('RHD', 'Right-Hand Drive (RHD)'), ('LHD', 'Left-Hand Drive (LHD)')], default='RHD', help_text='Select LHD for Nigeria/Ghana/Ethiopia. RHD for Kenya/SA/UK.', max_length=3)),
                ('location', models.CharField(default='Nairobi', max_length=100)),
                ('listing_type', models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Hire'), ('BOTH', 'For Sale & Hire')], default='SALE', help_text='Is this car for sale, for hire, or both?', max_length=10)),
                ('rent_price_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per day in Listing Currency (only required if For Hire)', max_digits=10, null=True)),
                ('min_hire_days', models.PositiveIntegerField(default=1, help_text='Minimum number of days this car can be rented')),
                ('is_available_for_rent', models.BooleanField(default=True)),
                ('mileage', models.IntegerField(default=0, help_text='Mileage in km')),
                ('engine_size', models.IntegerField(blank=True, help_text='Engine cc', null=True)),
                ('color', models.CharField(default='White', max_length=50)),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('FOREIGN', 'Foreign Used'), ('LOCAL', 'Local Used')], default='FOREIGN', max_length=20)),
                ('transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT')], default='AUTOMATIC', max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric')], default='PETROL', max_length=20)),
                ('body_type', models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup'), ('COUPE', 'Coupe'), ('BUS', 'Bus/Van'), ('TRUCK', 'Truck'), ('CONVERTIBLE', 'Convertible')], default='SUV', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('HIDDEN', 'Hidden (Plan Expired)')], default='AVAILABLE', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Awaiting Payment)'), ('PAID', 'Paid & Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='cars.car')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('car', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cars.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cars.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
