# Generated by Django 5.2.9 on 2026-01-04 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage_km',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup'), ('COUPE', 'Coupe'), ('BUS', 'Bus/Van'), ('TRUCK', 'Truck'), ('CONVERTIBLE', 'Convertible')], default='SUV', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('FOREIGN', 'Foreign Used'), ('LOCAL', 'Local Used')], default='FOREIGN', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(blank=True, help_text='Engine cc', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_available_for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Hire'), ('BOTH', 'For Sale & Hire')], default='SALE', help_text='Is this car for sale, for hire, or both?', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, help_text='Mileage in km'),
        ),
        migrations.AddField(
            model_name='car',
            name='min_hire_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of days this car can be rented'),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, help_text='e.g. KDA 123X (Hidden from public)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per day in KES (only required if For Hire)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric')], default='PETROL', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('HIDDEN', 'Hidden (Plan Expired)')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT')], default='AUTOMATIC', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Awaiting Payment)'), ('PAID', 'Paid & Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cars.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
