# Generated by Django 5.2.9 on 2025-12-25 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage_km',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup'), ('COUPE', 'Coupe'), ('BUS', 'Bus/Van'), ('TRUCK', 'Truck'), ('CONVERTIBLE', 'Convertible')], default='SUV', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('FOREIGN', 'Foreign Used'), ('LOCAL', 'Local Used')], default='FOREIGN', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(blank=True, help_text='Engine cc', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, help_text='Mileage in km'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric')], default='PETROL', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT')], default='AUTOMATIC', max_length=20),
        ),
        migrations.CreateModel(
            name='CarAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Page View'), ('WHATSAPP', 'WhatsApp Click'), ('CALL', 'Phone Call')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cars.car')),
            ],
        ),
    ]
