# Generated by Django 5.2.9 on 2025-12-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_mileage_km_car_body_type_car_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caranalytics',
            options={'verbose_name_plural': 'Car Leads'},
        ),
        migrations.AddField(
            model_name='caranalytics',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
