# Generated by Django 5.2.9 on 2025-12-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_mileage_km_car_body_type_car_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caranalytics',
            options={'verbose_name_plural': 'Car Leads'},
        ),
    ]
