# Generated by manual fix
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        # This points to the existing 0002 file found in your error logs
        ('cars', '0002_searchterm_remove_car_mileage_km_car_body_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='renter',
        ),
    ]