# Generated by Django 5.2.9 on 2025-12-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_mileage_km_car_body_type_car_color_and_more'),
    ]

    operations = [
        # 1. Create the NEW table (CarLead) - This runs normally
        migrations.CreateModel(
            name='CarLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Page View'), ('WHATSAPP', 'WhatsApp Click'), ('CALL', 'Phone Call')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Car Leads',
            },
        ),

        # 2. "Fake" Delete the old table
        # This prevents the "table does not exist" crash
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CarAnalytics',
                ),
            ],
            database_operations=[],  # <--- Empty list means "Do nothing in the DB"
        ),
    ]