# Generated by Django 5.2.9 on 2026-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carcomment_carlike_dealerfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine_size',
        ),
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.CharField(choices=[('2WD', '2WD (Two Wheel Drive)'), ('4WD', '4WD (Four Wheel Drive)'), ('AWD', 'AWD (All Wheel Drive)')], default='2WD', help_text='2WD, 4WD, or AWD', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_cc',
            field=models.IntegerField(blank=True, help_text='Engine cc (e.g. 2000)', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Coupe', 'Coupe'), ('Bus', 'Bus/Van'), ('Truck', 'Truck'), ('Convertible', 'Convertible')], default='SUV', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], default='Automatic', max_length=20),
        ),
    ]
