# Generated by Django 5.2.9 on 2025-12-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_caranalytics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='caranalytics',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
