# Generated by Django 5.2.9 on 2025-12-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_caranalytics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caranalytics',
            options={'verbose_name_plural': 'Car Leads'},
        ),
    ]
