# Generated by Django 5.2.9 on 2026-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_seed_maridady_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Coupe', 'Coupe'), ('Bus', 'Bus/Van'), ('Truck', 'Truck'), ('Convertible', 'Convertible'), ('Wagon', 'Station Wagon')], default='SUV', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Kiambu', 'Kiambu'), ('Thika', 'Thika'), ('Naivasha', 'Naivasha')], default='Nairobi', help_text='City or Town', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('KE', 'Kenya')], default='KE', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_side',
            field=models.CharField(choices=[('RHD', 'Right Hand Drive')], default='RHD', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_currency',
            field=models.CharField(default='KES', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per day in KES (only required if For Hire)', max_digits=10, null=True),
        ),
    ]
