# Generated by Django 6.0 on 2026-01-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_searchterm_carview_lead_delete_carlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, help_text='e.g. KDA 123X (Hidden from public)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('HIDDEN', 'Hidden (Plan Expired)')], default='AVAILABLE', max_length=20),
        ),
    ]
