# Generated by Django 6.0 on 2026-02-09 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_body_type_alter_car_city_alter_car_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_highest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
        migrations.RemoveField(
            model_name='carcomment',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carcomment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='dealerfollow',
            name='cars_dealer_followe_181a2b_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(choices=[('2WD', '2WD (Two Wheel Drive)'), ('4WD', '4WD (Four Wheel Drive)'), ('AWD', 'AWD (All Wheel Drive)')], default='2WD', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Hire'), ('BOTH', 'For Sale & Hire')], default='SALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='min_hire_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('HIDDEN', 'Hidden (Plan Expired)'), ('AUCTION', 'Live Auction')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='cars.car'),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='cars.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CarComment',
        ),
    ]
