# Generated by Django 5.2.9 on 2026-01-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_registration_number_alter_car_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available_for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Hire'), ('BOTH', 'For Sale & Hire')], default='SALE', help_text='Is this car for sale, for hire, or both?', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='min_hire_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of days this car can be rented'),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per day in KES (only required if For Hire)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('CONFIRMED', 'Confirmed (Awaiting Payment)'), ('PAID', 'Paid & Active'), ('COMPLETED', 'Returned & Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
