# Generated by Django 5.2.9 on 2026-01-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_carbooking_car_remove_carbooking_customer_and_more'),
        ('payments', '0004_alter_payment_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarBooking',
        ),
    ]
